name: 部署文档

on:
  push:
    branches:
      - main
      - writing
      - dev

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 深度清理Corepack
        run: |
          # 清理所有已知缓存路径
          sudo rm -rf ~/.cache/node/corepack
          sudo rm -rf /opt/hostedtoolcache/node/corepack
          sudo rm -rf "$(npm get prefix)/lib/node_modules/corepack"
          sudo rm -rf /tmp/corepack-*
          echo "清理完成时间: $(date)"  # 调试时间戳

      - name: 安装Node.js（绕过Corepack）
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          disable-corepack: true  # 关键参数：禁用Corepack
          cache: pnpm

      - name: 强制安装pnpm（直接npm安装）
        run: |
          npm install -g pnpm@9.0.5 --registry=https://registry.npmmirror.com
          pnpm -v

      - name: 安装依赖
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies=false
          pnpm store prune  # 清理无效存储

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm run docs:build
          touch src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist